/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triangular_storage;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        TriangularStorage triangularStorage = new TriangularStorage();
        List<Integer> inputValues = new ArrayList<>();

        try {
            Scanner input = new Scanner(System.in);
            while (input.hasNext()) {
                int nextInt = cleanInput(input.nextLine());
                if (nextInt == 0)
                    break;

                inputValues.add(nextInt);
            }

            if (inputValues.size() % 2 != 0)
                throw new Exception("Must provide an even number of input values or a y value for each x value");

            while (inputValues.size() > 0) {
                int x = inputValues.remove(inputValues.size() - 1);
                int y = inputValues.remove(inputValues.size() - 1);
                System.out.println(triangularStorage.answer(x, y));
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private static int cleanInput(String line) throws Exception {
        try {
            return Integer.parseInt(line.trim());
        } catch (Exception e) {
            throw new Exception("Only numbers are allowed as input");
        }
    }

}
